service: git-profiler-bot
app: git-profiler-bot
tenant: aashutoshrathi

provider:
  name: aws
  runtime: python3.7
  region: ap-south-1
  environment:
    TELEGRAM_TOKEN: ${file(./serverless.env.yml):TELEGRAM_TOKEN, ''}
    CONTRI_API: ${file(./serverless.env.yml):CONTRI_API, ''}
    GH_API: ${file(./serverless.env.yml):GH_API, ''}

functions:
  webhook:
    handler: handler.webhook
    events:
      - http: POST /

  set_webhook:
    handler: handler.set_webhook
    events:
      - http: POST /set_webhook

plugins:
- serverless-python-requirements
